### ISSUE TITLE
compile failed due to  E0507

### ISSUE THREAD

**Issue by mashomee** [frewsxcv/rust-notifica#1]
rust code is simple like example
``` 
use notifica::*;

 fn main() {
     notifica::notify("Hello", "World");
 }
 
```
compile failed. error:

>  Compiling notifica v1.0.0
> error[E0507]: cannot move out of borrowed content
>   --> C:\Users\s-pc\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\notifica-1.0.0\src\lib.rs:71:9
>  |
> 71 |         self.0.uninit();
>    |         ^^^^^^ cannot move out of borrowed content
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0507`.
> error: Could not compile `notifica`.
> 
> To learn more, run the command again with --verbose.

**Comment by vbrandl** [comment]
Changing teardown to take ownership instead of a mutable reference should fix this.
