### ISSUE TITLE
Sending multiple notifications on MacOS fails

### ISSUE THREAD

**Issue by ghost** [frewsxcv/rust-notifica#11]
MacOS panics with the error below when trying to send multiple notifications.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: AlreadySet }
```

Example
```rust
fn main() {
    let app = "testapp";
    notifica::notify(app, "test1"); // succeeds
    notifica::notify(app, "test2"); // errors 
}
```

The underlying notification library used for MacOS tracks if the application name has been set, and will error (https://github.com/h4llow3En/mac-notification-sys/blob/master/src/lib.rs#L146) when trying to set the application name again. `::notify()` should handle this error gracefully.

PR (https://github.com/frewsxcv/rust-notifica/pull/10) is refactoring calls to `unwrap()` and return the library errors for `notifica`,  although this issue would still be present (it wouldn't panic, but the early return would not trigger additional notifications). If https://github.com/frewsxcv/rust-notifica/pull/10 is the direction for error handling, I can catch the `ApplicationError::AlreadySet` locally and continue execution, otherwise return all other errors to the caller. 

Nonetheless I can fix this, just need to know what branch to branch from.

**Comment by frewsxcv** [comment]
good catch! i just merged the other pull requests, so you should be good to branch off master

**Comment by frewsxcv** [comment]
fixed in https://github.com/frewsxcv/rust-notifica/pull/22
